---
- name: Update the timezone
  timezone:
    name: Asia/Jerusalem

- name: Enable EPEL Repository on CentOS 7
  yum:
    name:
      - epel-release
      - bash-completion
    state: latest
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
  become: true

- name: Upgrade all packages.
  yum:
    name: '*'
    state: latest
    lock_timeout: 180
  tags: prep

# Moved to cloud init packages
- name: Install requierd apps.
  yum:
    name:
    - cloud-utils-growpart
    - wget
    - curl
    - nfs-utils
    state: latest
    lock_timeout: 180
  tags: prep

- name: Configure Disks
  shell: |
    growpart /dev/sda 2
    pvresize /dev/sda2
    lvextend -r -l +100%FREE /dev/centos/root > ~/disks.log
  args:
    creates: ~/disks.log

- name: Update FQDN
  hostname:
    name: "{{ ansible_hostname }}.{{ domain_name }}"

- name: Configure policy and state of SELinux
  selinux:
    state: disabled
  notify: reboot

- debug: "msg={{ groups['all'] }}"

- name: Update the /etc/hosts file with node name
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ item }}"
    line: "{{ item }}\t{{ hostvars[item]['ansible_hostname']}}.{{ domain_name }}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
    backup: yes
  register: etchostsupdate
  with_items: "{{ groups['all'] }}"

- name: Enable PubkeyAuthentication.
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'
  notify: 
    - restart sshd

- name: Disable PasswordAuthentication.
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  notify: 
    - restart sshd

- name: Disable sudo password
  lineinfile:
    path: /etc/sudoers
    regexp: '^#%wheel        ALL=(ALL)       NOPASSWD: ALL'
    line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
  
- name: UPdate ARP setting on /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{item}}"
  loop:
    - net.ipv4.conf.eth0.arp_ignore=0
    - net.ipv4.conf.eth0.arp_announce=0