---
- name: Create a mountable directory if it does not exist
  file:
    path: /mnt/ezmeral-nfs
    state: directory
    mode: "775"
  tags: nfs-client
  become: true

- name: Mount an NFS volume
  mount:
    src: "{{ hostvars[groups['gateway'][0]]['ansible_default_ipv4']['address'] }}:/mnt/ezmeral-data"
    path: /mnt/ezmeral-nfs
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs
  become: true
