---
# hpecp cli docs: https://github.com/hpe-container-platform-community/hpecp-python-library
- name: Check if gateway is installed
  shell: ~/.local/bin/hpecp gateway list --output text
  register: gw_status

- name: lockdown status
  shell: | 
    ~/.local/bin/hpecp lock list -output json | grep -c 'locked": false,'
  register: lockdown_status 

- debug: "msg={{ lockdown_status }}"

- name: Enter lockdown
  shell: ~/.local/bin/hpecp lock create "Installing Gateway"
  when: gw_status.stdout == "" and lockdown_status.stdout == "1"

- name: Configure gateway
  shell: |
    LOG_LEVEL=DEBUG ~/.local/bin/hpecp gateway create-with-ssh-key --ip {{ item }} --proxy-node-hostname "{{ hostvars[item]['ansible_nodename'] }}" --ssh-key-file {{ez_folder}}/ssh_host_rsa_key
  with_items: "{{ groups['gateway'] }}"
  when: gw_status.stdout == ""
  
- name: Exit lockdown
  shell: ~/.local/bin/hpecp lock delete-all --timeout-secs 1800
  when: gw_status.stdout == ""

- name: Check if workers installed
  shell: ~/.local/bin/hpecp k8sworker list --output text
  register: k8s_workers

# - debug: "msg={{ hostvars[groups['workers']]['ansible_default_ipv4']['address'] }}"

- name: Add k8s workers
  shell: ~/.local/bin/hpecp k8sworker create_with_ssh_key --ip {{ item }} --ssh_key_file {{ez_folder}}/ssh_host_rsa_key --ephemeral-disks /dev/sdb --wait-for-operation-secs 600
  with_items: "{{ groups['workers'] }}"
  when: k8s_workers.stdout == ""

  # TODO:
  # choose disk with variable
- name: Get k8s Clusters
  shell: ~/.local/bin/hpecp k8scluster list --columns name -o text | grep -c 'k8scluster'
  register: k8s_clusters
  failed_when: k8s_clusters.rc != 1 and k8s_clusters.rc != 0
  
- debug: "msg={{ k8s_clusters }}"

- name: Get k8s workers information 
  shell: "~/.local/bin/hpecp k8sworker get /api/v2/worker/k8shost/ -o json"
  register: output
  ignore_errors: True
- set_fact:
    workers: "{{ output.stdout | from_json }}"
- set_fact:
    worker_ids: "{{ workers | json_query(jmesquery) }}"
  vars:
    jmesquery: "_embedded.k8shosts[]._links.self.href"
- set_fact:
    master_list: "{{ worker_ids[:1] | map('regex_replace', '$', ':master') | list }}"
- set_fact:
    worker_list: "{{ worker_ids[1:] | map('regex_replace', '$', ':worker') | list }}"
- set_fact:
    k8shost_list: "{{ master_list + worker_list }}"

- debug: "msg={{ worker_list }}"
- debug: "msg={{ master_list }}"

# - name: Creating K8s cluster
#   shell: |
#     ~/.local/bin/hpecp k8scluster create \
#     --name k8scluster \
#     --k8s_version "{{ k8s_version }}" \
#     --k8shosts-config {{ k8shost_list | join(',')  }} \
#   ignore_errors: True
#   when: k8s_clusters.stdout == "0"