---
- name: prep the servers
  hosts: all
  vars_files:
    - roles/common/vars/vars.yml
  become: true
  roles:
    - prep

# - hosts: controller
#   vars_files:
#     - roles/common/vars/vars.yml
#   roles:
#     - controller
#     - hpecp

- hosts: gateway
  vars_files:
    - roles/common/vars/vars.yml
  roles:
    - nfs-server
  become: true